# Generated by Django 4.0.4 on 2022-06-07 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='address',
            new_name='place_id',
        ),
        migrations.RemoveField(
            model_name='place',
            name='maps_url',
        ),
        migrations.RemoveField(
            model_name='place',
            name='name',
        ),
        migrations.RemoveField(
            model_name='place',
            name='website',
        ),
    ]
