# Generated by Django 4.0.4 on 2022-05-31 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excursion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excursion',
            old_name='place_id',
            new_name='place',
        ),
    ]
