# Generated by Django 4.0.4 on 2022-06-08 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excursion', '0002_rename_place_id_excursion_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excursion',
            old_name='place',
            new_name='place_id',
        ),
    ]
