# Generated by Django 4.0.4 on 2022-06-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursion', '0003_rename_place_excursion_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='date',
            field=models.CharField(max_length=255),
        ),
    ]
