# Generated by Django 4.0.4 on 2022-06-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursion', '0004_alter_excursion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='date',
            field=models.DateField(),
        ),
    ]
