# Generated by Django 4.0.4 on 2022-06-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursion', '0005_alter_excursion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='place_id',
            field=models.CharField(max_length=255),
        ),
    ]
